## Preprocessing

In [14]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [15]:
# Drop the non-beneficial ID columns, 'EIN'.

application_df = application_df.drop(columns = ['EIN'], axis = 1)

In [16]:
# Determine the number of unique values in each column.

[(i, len(application_df[i].unique())) for i in application_df.columns]

[('NAME', 19568),
 ('APPLICATION_TYPE', 17),
 ('AFFILIATION', 6),
 ('CLASSIFICATION', 71),
 ('USE_CASE', 5),
 ('ORGANIZATION', 4),
 ('STATUS', 2),
 ('INCOME_AMT', 9),
 ('SPECIAL_CONSIDERATIONS', 2),
 ('ASK_AMT', 8747),
 ('IS_SUCCESSFUL', 2)]

In [17]:
# Look at APPLICATION_TYPE value counts for binning

application_df.APPLICATION_TYPE.value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [18]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_df.APPLICATION_TYPE.value_counts()[application_df.APPLICATION_TYPE.value_counts() < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [19]:
# Look at CLASSIFICATION value counts for binning

application_df.CLASSIFICATION.value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [20]:
# You may find it helpful to look at CLASSIFICATION value counts >1

application_df.CLASSIFICATION.value_counts()[application_df.CLASSIFICATION.value_counts() > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [21]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(application_df.CLASSIFICATION.value_counts()[application_df.CLASSIFICATION.value_counts() < 100].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [9]:
# Look at NAME value counts for binning
application_df['NAME'].value_counts()

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [22]:
# Choose a cutoff value and create a list of names to be replaced
names_to_replace = list(application_df['NAME'].value_counts()[application_df['NAME'].value_counts() < 50].index)

# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(
        name, "Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                 24545
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
MONTANA 4-H FOUNDATION INC                                              107
HONOR SOCIETY OF PHI KAPPA PHI                                          107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
AIR FORCE ASSOCIATION                                                    99
WORKERS UNITED                                                           97
GAMMA THETA UPSILON                                                      92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                               91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                  87
ROTARY INTERNATIONAL                                                     84
CALIFORNIA GARDEN CLUBS INC                                              76
SWEET ADELINES INTERNATIONAL                                             73
DISABLED AMERICAN VETERANS                                               73
KLEIN SUPPORT GROUPS INC                                                 69
CLEARCREEK I S D SUPPORT GROUPS                                          60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                 58
CISD EDUCATIONAL SUPPORT GROUPS INC                                      57
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC           57
SONS OF CONFEDERATE VETERANS INC                                         56
SLOW FOOD USA INC                                                        55
NATIONAL YOUNG MENS SERVICE LEAGUE                                       54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                              52
LAMBDA THETA ALPHA                                                       52
UNITED FEDERATION OF DOLL CLUBS INC                                      50
UNIVERSITY OF FLORIDA                                                    50
Name: NAME, dtype: int64

In [23]:
# Convert categorical data to numeric with `pd.get_dummies`

application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AIR FORCE ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CALIFORNIA GARDEN CLUBS INC,NAME_CISD EDUCATIONAL SUPPORT GROUPS INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [24]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
y = application_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
x_train,x_test, y_train, y_test = train_test_split(X, y, random_state = 123)

In [25]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled  = x_scaler.transform(x_test)

## Compile, Train and Evaluate the Model

In [26]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

input_features = x_train_scaled.shape[1]
hidden_nodes1  = 30
hidden_nodes2  = 60
optimized_model_1 = tf.keras.models.Sequential()

# First hidden layer
optimized_model_1.add(tf.keras.layers.Dense(units=hidden_nodes1, input_dim=input_features, activation='relu'))
# Second hidden layer
optimized_model_1.add(tf.keras.layers.Dense(units=hidden_nodes2, activation='relu'))

# Output layer
optimized_model_1.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
optimized_model_1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 30)                3060

 dense_1 (Dense)             (None, 60)                1860

 dense_2 (Dense)             (None, 1)                 61

=================================================================
Total params: 4,981
Trainable params: 4,981
Non-trainable params: 0
_________________________________________________________________

In [27]:
# Compile the model

optimized_model_1.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [28]:
# Train the model

fit_model_1 = optimized_model_1.fit(x_train_scaled, y_train, validation_split = 0.15, epochs = 50)

Epoch 1/50
684/684 [==============================] - 3s 3ms/step - loss: 0.5118 - accuracy: 0.7422 - val_loss: 0.4868 - val_accuracy: 0.7587
Epoch 2/50
684/684 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7607 - val_loss: 0.4897 - val_accuracy: 0.7600
Epoch 3/50
684/684 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7624 - val_loss: 0.4802 - val_accuracy: 0.7665
Epoch 4/50
684/684 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7651 - val_loss: 0.4806 - val_accuracy: 0.7634
Epoch 5/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4738 - accuracy: 0.7647 - val_loss: 0.4802 - val_accuracy: 0.7670
Epoch 6/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4726 - accuracy: 0.7651 - val_loss: 0.4775 - val_accuracy: 0.7668
Epoch 7/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4710 - accuracy: 0.7676 - val_loss: 0.4831 - val_accuracy: 0.7673
Epoch 8/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4710 - accuracy: 0.7677 - val_loss: 0.4813 - val_accuracy: 0.7652
Epoch 9/50
684/684 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7681 - val_loss: 0.4818 - val_accuracy: 0.7629
Epoch 10/50
684/684 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7675 - val_loss: 0.4779 - val_accuracy: 0.7689
Epoch 11/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4683 - accuracy: 0.7674 - val_loss: 0.4819 - val_accuracy: 0.7647
Epoch 12/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4676 - accuracy: 0.7693 - val_loss: 0.4820 - val_accuracy: 0.7699
Epoch 13/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4674 - accuracy: 0.7704 - val_loss: 0.4809 - val_accuracy: 0.7665
Epoch 14/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4665 - accuracy: 0.7697 - val_loss: 0.4817 - val_accuracy: 0.7624
Epoch 15/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4657 - accuracy: 0.7707 - val_loss: 0.4802 - val_accuracy: 0.7647
Epoch 16/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4657 - accuracy: 0.7706 - val_loss: 0.4824 - val_accuracy: 0.7655
Epoch 17/50
684/684 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7714 - val_loss: 0.4794 - val_accuracy: 0.7637
Epoch 18/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4644 - accuracy: 0.7708 - val_loss: 0.4776 - val_accuracy: 0.7701
Epoch 19/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4643 - accuracy: 0.7727 - val_loss: 0.4828 - val_accuracy: 0.7699
Epoch 20/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4637 - accuracy: 0.7723 - val_loss: 0.4804 - val_accuracy: 0.7699
Epoch 21/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4630 - accuracy: 0.7716 - val_loss: 0.4812 - val_accuracy: 0.7676
Epoch 22/50
684/684 [==============================] - 1s 2ms/step - loss: 0.4630 - accuracy: 0.7724 - val_loss: 0.4832 - val_accuracy: 0.7681
Epoch 23/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4629 - accuracy: 0.7716 - val_loss: 0.4794 - val_accuracy: 0.7668
Epoch 24/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4622 - accuracy: 0.7722 - val_loss: 0.4844 - val_accuracy: 0.7686
Epoch 25/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4625 - accuracy: 0.7723 - val_loss: 0.4852 - val_accuracy: 0.7639
Epoch 26/50
684/684 [==============================] - 1s 2ms/step - loss: 0.4616 - accuracy: 0.7720 - val_loss: 0.4803 - val_accuracy: 0.7668
Epoch 27/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4612 - accuracy: 0.7739 - val_loss: 0.4823 - val_accuracy: 0.7663
Epoch 28/50
684/684 [==============================] - 3s 4ms/step - loss: 0.4614 - accuracy: 0.7731 - val_loss: 0.4851 - val_accuracy: 0.7673
Epoch 29/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4612 - accuracy: 0.7737 - val_loss: 0.4829 - val_accuracy: 0.7686
Epoch 30/50
684/684 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.7727 - val_loss: 0.4840 - val_accuracy: 0.7668
Epoch 31/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4605 - accuracy: 0.7732 - val_loss: 0.4815 - val_accuracy: 0.7665
Epoch 32/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4607 - accuracy: 0.7730 - val_loss: 0.4823 - val_accuracy: 0.7694
Epoch 33/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4602 - accuracy: 0.7734 - val_loss: 0.4831 - val_accuracy: 0.7725
Epoch 34/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4600 - accuracy: 0.7742 - val_loss: 0.4847 - val_accuracy: 0.7670
Epoch 35/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4589 - accuracy: 0.7737 - val_loss: 0.4859 - val_accuracy: 0.7686
Epoch 36/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4589 - accuracy: 0.7735 - val_loss: 0.4843 - val_accuracy: 0.7701
Epoch 37/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4589 - accuracy: 0.7736 - val_loss: 0.4861 - val_accuracy: 0.7639
Epoch 38/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4589 - accuracy: 0.7734 - val_loss: 0.4827 - val_accuracy: 0.7678
Epoch 39/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4591 - accuracy: 0.7749 - val_loss: 0.4855 - val_accuracy: 0.7670
Epoch 40/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4589 - accuracy: 0.7748 - val_loss: 0.4860 - val_accuracy: 0.7663
Epoch 41/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4582 - accuracy: 0.7741 - val_loss: 0.4856 - val_accuracy: 0.7701
Epoch 42/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4580 - accuracy: 0.7742 - val_loss: 0.4870 - val_accuracy: 0.7668
Epoch 43/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4582 - accuracy: 0.7749 - val_loss: 0.4856 - val_accuracy: 0.7704
Epoch 44/50
684/684 [==============================] - 2s 2ms/step - loss: 0.4581 - accuracy: 0.7749 - val_loss: 0.4871 - val_accuracy: 0.7608
Epoch 45/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4579 - accuracy: 0.7751 - val_loss: 0.4874 - val_accuracy: 0.7650
Epoch 46/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4578 - accuracy: 0.7752 - val_loss: 0.4903 - val_accuracy: 0.7600
Epoch 47/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4573 - accuracy: 0.7755 - val_loss: 0.4873 - val_accuracy: 0.7644
Epoch 48/50
684/684 [==============================] - 3s 4ms/step - loss: 0.4576 - accuracy: 0.7753 - val_loss: 0.4867 - val_accuracy: 0.7642
Epoch 49/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4575 - accuracy: 0.7754 - val_loss: 0.4888 - val_accuracy: 0.7634
Epoch 50/50
684/684 [==============================] - 2s 3ms/step - loss: 0.4570 - accuracy: 0.7759 - val_loss: 0.4925 - val_accuracy: 0.7663

In [31]:
# Evaluate the model using the test data
model_loss_1, model_accuracy_1 = optimized_model_1.evaluate(x_test_scaled, y_test, verbose = 2)
print(f"Loss: {round(model_loss_1, 3)}, Accuracy: {round(model_accuracy_1 * 100, 2)}%")

268/268 - 0s - loss: 0.4868 - accuracy: 0.7657 - 345ms/epoch - 1ms/step
Loss: 0.487, Accuracy: 76.57%

In [33]:
# Export our model to HDF5 file

optimized_model_1.save('AlphabetSoupCharity_Optimization_1.h5')

## Compile, Train and Evaluate the Model

### Model 2

In [34]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

input_features = x_train_scaled.shape[1]
hidden_nodes1  = 50
hidden_nodes2  = 100
hidden_nodes3  = 200
optimized_model_2 = tf.keras.models.Sequential()

# First hidden layer
optimized_model_2.add(tf.keras.layers.Dense(units=hidden_nodes1, input_dim=input_features, activation='relu'))
# Second hidden layer
optimized_model_2.add(tf.keras.layers.Dense(units=hidden_nodes2, activation='relu'))
# Third hidden layer
optimized_model_2.add(tf.keras.layers.Dense(units=hidden_nodes3, activation='relu'))
# Output layer
optimized_model_2.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
optimized_model_2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 50)                5100

 dense_4 (Dense)             (None, 100)               5100

 dense_5 (Dense)             (None, 200)               20200

 dense_6 (Dense)             (None, 1)                 201

=================================================================
Total params: 30,601
Trainable params: 30,601
Non-trainable params: 0
_________________________________________________________________

In [35]:
# Compile the model

optimized_model_2.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [36]:
# Train the model

fit_model_2 = optimized_model_2.fit(x_train_scaled, y_train, validation_split = 0.15, epochs = 75)

Epoch 1/75
684/684 [==============================] - 4s 3ms/step - loss: 0.5033 - accuracy: 0.7492 - val_loss: 0.4840 - val_accuracy: 0.7593
Epoch 2/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4804 - accuracy: 0.7615 - val_loss: 0.4810 - val_accuracy: 0.7699
Epoch 3/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4759 - accuracy: 0.7632 - val_loss: 0.4770 - val_accuracy: 0.7691
Epoch 4/75
684/684 [==============================] - 4s 6ms/step - loss: 0.4737 - accuracy: 0.7667 - val_loss: 0.4798 - val_accuracy: 0.7694
Epoch 5/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4723 - accuracy: 0.7685 - val_loss: 0.4778 - val_accuracy: 0.7694
Epoch 6/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4710 - accuracy: 0.7678 - val_loss: 0.4792 - val_accuracy: 0.7665
Epoch 7/75
684/684 [==============================] - 3s 5ms/step - loss: 0.4697 - accuracy: 0.7696 - val_loss: 0.4802 - val_accuracy: 0.7712
Epoch 8/75
684/684 [==============================] - 4s 6ms/step - loss: 0.4684 - accuracy: 0.7699 - val_loss: 0.4824 - val_accuracy: 0.7707
Epoch 9/75
684/684 [==============================] - 3s 5ms/step - loss: 0.4681 - accuracy: 0.7705 - val_loss: 0.4807 - val_accuracy: 0.7714
Epoch 10/75
684/684 [==============================] - 3s 5ms/step - loss: 0.4671 - accuracy: 0.7710 - val_loss: 0.4796 - val_accuracy: 0.7689
Epoch 11/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4663 - accuracy: 0.7710 - val_loss: 0.4803 - val_accuracy: 0.7694
Epoch 12/75
684/684 [==============================] - 2s 4ms/step - loss: 0.4658 - accuracy: 0.7701 - val_loss: 0.4771 - val_accuracy: 0.7709
Epoch 13/75
684/684 [==============================] - 2s 4ms/step - loss: 0.4655 - accuracy: 0.7713 - val_loss: 0.4805 - val_accuracy: 0.7694
Epoch 14/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4648 - accuracy: 0.7730 - val_loss: 0.4810 - val_accuracy: 0.7722
Epoch 15/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4638 - accuracy: 0.7717 - val_loss: 0.4845 - val_accuracy: 0.7709
Epoch 16/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4634 - accuracy: 0.7731 - val_loss: 0.4810 - val_accuracy: 0.7694
Epoch 17/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4636 - accuracy: 0.7712 - val_loss: 0.4813 - val_accuracy: 0.7696
Epoch 18/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4621 - accuracy: 0.7732 - val_loss: 0.4814 - val_accuracy: 0.7683
Epoch 19/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4616 - accuracy: 0.7732 - val_loss: 0.4832 - val_accuracy: 0.7694
Epoch 20/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4614 - accuracy: 0.7753 - val_loss: 0.4805 - val_accuracy: 0.7709
Epoch 21/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4608 - accuracy: 0.7737 - val_loss: 0.4846 - val_accuracy: 0.7686
Epoch 22/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4602 - accuracy: 0.7734 - val_loss: 0.4829 - val_accuracy: 0.7683
Epoch 23/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4601 - accuracy: 0.7739 - val_loss: 0.4884 - val_accuracy: 0.7616
Epoch 24/75
684/684 [==============================] - 2s 4ms/step - loss: 0.4599 - accuracy: 0.7742 - val_loss: 0.4859 - val_accuracy: 0.7686
Epoch 25/75
684/684 [==============================] - 2s 4ms/step - loss: 0.4586 - accuracy: 0.7748 - val_loss: 0.4885 - val_accuracy: 0.7689
Epoch 26/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4591 - accuracy: 0.7759 - val_loss: 0.4872 - val_accuracy: 0.7681
Epoch 27/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4583 - accuracy: 0.7756 - val_loss: 0.4844 - val_accuracy: 0.7689
Epoch 28/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4582 - accuracy: 0.7745 - val_loss: 0.4893 - val_accuracy: 0.7696
Epoch 29/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4578 - accuracy: 0.7753 - val_loss: 0.4909 - val_accuracy: 0.7678
Epoch 30/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4581 - accuracy: 0.7756 - val_loss: 0.4972 - val_accuracy: 0.7678
Epoch 31/75
684/684 [==============================] - 2s 4ms/step - loss: 0.4570 - accuracy: 0.7750 - val_loss: 0.4986 - val_accuracy: 0.7660
Epoch 32/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4569 - accuracy: 0.7760 - val_loss: 0.4926 - val_accuracy: 0.7701
Epoch 33/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4566 - accuracy: 0.7752 - val_loss: 0.4992 - val_accuracy: 0.7676
Epoch 34/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4561 - accuracy: 0.7757 - val_loss: 0.5105 - val_accuracy: 0.7683
Epoch 35/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4566 - accuracy: 0.7754 - val_loss: 0.4946 - val_accuracy: 0.7678
Epoch 36/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4554 - accuracy: 0.7766 - val_loss: 0.5003 - val_accuracy: 0.7663
Epoch 37/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4554 - accuracy: 0.7769 - val_loss: 0.5029 - val_accuracy: 0.7668
Epoch 38/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4555 - accuracy: 0.7764 - val_loss: 0.5029 - val_accuracy: 0.7660
Epoch 39/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4550 - accuracy: 0.7757 - val_loss: 0.5020 - val_accuracy: 0.7676
Epoch 40/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4547 - accuracy: 0.7762 - val_loss: 0.4949 - val_accuracy: 0.7696
Epoch 41/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4556 - accuracy: 0.7753 - val_loss: 0.5047 - val_accuracy: 0.7668
Epoch 42/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4542 - accuracy: 0.7758 - val_loss: 0.5070 - val_accuracy: 0.7720
Epoch 43/75
684/684 [==============================] - 3s 5ms/step - loss: 0.4536 - accuracy: 0.7752 - val_loss: 0.5107 - val_accuracy: 0.7681
Epoch 44/75
684/684 [==============================] - 3s 5ms/step - loss: 0.4553 - accuracy: 0.7763 - val_loss: 0.5127 - val_accuracy: 0.7665
Epoch 45/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4541 - accuracy: 0.7761 - val_loss: 0.5208 - val_accuracy: 0.7670
Epoch 46/75
684/684 [==============================] - 3s 5ms/step - loss: 0.4556 - accuracy: 0.7757 - val_loss: 0.5122 - val_accuracy: 0.7701
Epoch 47/75
684/684 [==============================] - 5s 7ms/step - loss: 0.4529 - accuracy: 0.7772 - val_loss: 0.5099 - val_accuracy: 0.7676
Epoch 48/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4535 - accuracy: 0.7760 - val_loss: 0.5121 - val_accuracy: 0.7676
Epoch 49/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4533 - accuracy: 0.7759 - val_loss: 0.5177 - val_accuracy: 0.7673
Epoch 50/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4532 - accuracy: 0.7770 - val_loss: 0.5133 - val_accuracy: 0.7676
Epoch 51/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4527 - accuracy: 0.7772 - val_loss: 0.5149 - val_accuracy: 0.7699
Epoch 52/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4527 - accuracy: 0.7767 - val_loss: 0.5146 - val_accuracy: 0.7691
Epoch 53/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4530 - accuracy: 0.7771 - val_loss: 0.5134 - val_accuracy: 0.7673
Epoch 54/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4526 - accuracy: 0.7764 - val_loss: 0.5211 - val_accuracy: 0.7668
Epoch 55/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4528 - accuracy: 0.7774 - val_loss: 0.5171 - val_accuracy: 0.7707
Epoch 56/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4533 - accuracy: 0.7769 - val_loss: 0.5106 - val_accuracy: 0.7683
Epoch 57/75
684/684 [==============================] - 2s 4ms/step - loss: 0.4518 - accuracy: 0.7769 - val_loss: 0.5232 - val_accuracy: 0.7707
Epoch 58/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4522 - accuracy: 0.7767 - val_loss: 0.5191 - val_accuracy: 0.7670
Epoch 59/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4517 - accuracy: 0.7772 - val_loss: 0.5187 - val_accuracy: 0.7712
Epoch 60/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4516 - accuracy: 0.7773 - val_loss: 0.5245 - val_accuracy: 0.7689
Epoch 61/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4528 - accuracy: 0.7781 - val_loss: 0.5216 - val_accuracy: 0.7691
Epoch 62/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4522 - accuracy: 0.7770 - val_loss: 0.5277 - val_accuracy: 0.7689
Epoch 63/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4513 - accuracy: 0.7778 - val_loss: 0.5208 - val_accuracy: 0.7701
Epoch 64/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4513 - accuracy: 0.7775 - val_loss: 0.5268 - val_accuracy: 0.7670
Epoch 65/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4513 - accuracy: 0.7784 - val_loss: 0.5239 - val_accuracy: 0.7657
Epoch 66/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4517 - accuracy: 0.7778 - val_loss: 0.5305 - val_accuracy: 0.7686
Epoch 67/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4513 - accuracy: 0.7769 - val_loss: 0.5257 - val_accuracy: 0.7704
Epoch 68/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4509 - accuracy: 0.7780 - val_loss: 0.5430 - val_accuracy: 0.7691
Epoch 69/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4511 - accuracy: 0.7775 - val_loss: 0.5355 - val_accuracy: 0.7676
Epoch 70/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4512 - accuracy: 0.7777 - val_loss: 0.5475 - val_accuracy: 0.7657
Epoch 71/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4529 - accuracy: 0.7773 - val_loss: 0.5311 - val_accuracy: 0.7707
Epoch 72/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4507 - accuracy: 0.7767 - val_loss: 0.5295 - val_accuracy: 0.7683
Epoch 73/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4501 - accuracy: 0.7785 - val_loss: 0.5527 - val_accuracy: 0.7683
Epoch 74/75
684/684 [==============================] - 3s 4ms/step - loss: 0.4510 - accuracy: 0.7775 - val_loss: 0.5269 - val_accuracy: 0.7694
Epoch 75/75
684/684 [==============================] - 2s 3ms/step - loss: 0.4509 - accuracy: 0.7777 - val_loss: 0.5411 - val_accuracy: 0.7668

In [37]:
# Evaluate the model using the test data
model_loss_2, model_accuracy_2 = optimized_model_2.evaluate(x_test_scaled, y_test, verbose = 2)
print(f"Loss: {round(model_loss_2, 3)}, Accuracy: {round(model_accuracy_2 * 100, 2)}%")

268/268 - 0s - loss: 0.5235 - accuracy: 0.7669 - 367ms/epoch - 1ms/step
Loss: 0.524, Accuracy: 76.69%

In [38]:
# Export our model to HDF5 file

optimized_model_2.save('AlphabetSoupCharity_Optimization_2.h5')

# Analysis Report

## 1.  Overview:

A nonprofit foundation named `Alphabet Soup` aims to build a deep learning model that can help them to predict whether or not the applicants will be successful for funding. As there are only two categories i.e. successful and not successful, which makes it a binary classification problem. With the dataset provided, the goal is to build a binary classifier that could predict whether applicants will be successful if funded by Alphabet Soup.

## 2. Results

* ### Data Preprocessing:
  * What variable(s) are the target(s) for your model?
    * The *`IS_SUCCESSFUL`* column from application_df is the target variable, this is what we are trying to predict. This shows if the money was used effectively.

  * What variable(s) are the features for your model?
    * **The feature variables we used are:**
      1. `APPLICATION_TYPE`       --> Alphabet Soup application type

      2. `AFFILIATION`            --> Affiliated sector of industry

      3. `CLASSIFICATION`         --> Government organization classification

      4. `USE_CASE`               --> Use case for funding

      5. `ORGANIZATION`           --> Organization type

      6. `STATUS`                 --> Active status

      7. `INCOME_AMT`             --> Income classification

      8. `SPECIAL_CONSIDERATIONS` --> Special considerations for application

      9. `ASK_AMT`                --> Funding amount requested**

  * What variable(s) should be removed from the input data because they are neither targets nor features?
    * The *`EIN`* and *`NAME`* columns are identification columns that typically provide unique identifiers for each organization. These columns usually have no direct impact on the target variable and can be dropped without affecting the model's accuracy.

* ### Compiling, Training, and Evaluating the Model:

  * How many neurons, layers, and activation functions did you select for your neural network model, and why?
    * For this challenge I have implemented `3` different deep learning models, one of them is a simple model while the other two are the optimized versions of deep learning models with different number of hidden layers, different number on neurons, different activation functions, and different number of epochs.
        ### Simple Neural Network:  
        * The first neural network model named *`simple_model`*, is a two-layer architecture with a specific choice for the number of neurons, layers, and activation functions. By selecting 15 neurons in the first hidden layer (units_1 = 15), 25 neurons in the second hidden layer (units_2 = 25), and using the `ReLU` activation function (activation = "relu") for both hidden layers. The number of epoch for the *`simple_model`* were set 30. The choice of `ReLU` activation helps introduce non-linearity and allows the model to learn complex relationships between the input features and the target variable.

        <img src="images/simple_model.PNG" alt="Alternative text" />
        
        I used a single neuron in the output layer (units = 1) with a `sigmoid` activation function (activation = "sigmoid") to model the binary classification problem. The sigmoid activation function maps the output to a range between `0` and `1`, representing the probability of the positive class.
        
        <img src="images/simple_model_result.PNG" alt="Alternative text" />

        ### Optimized Neural Networks:
     
        * The first neural network model named *`first_model`*, is a two-layer architecture with a specific choice for the number of neurons, layers, and activation functions. By selecting 20 neurons in the first hidden layer (units_1 = 20), 30 neurons in the second hidden layer (units_2 = 30), and using the ReLU activation function (activation="relu") for both hidden layers. The number of epoch for the *`first_model`* were set 50. The choice of `ReLU` activation helps introduce non-linearity and allows the model to learn complex relationships between the input features and the target variable.

        <img src="images/first_model.PNG" alt="Alternative text" />
        
        I used a single neuron in the output layer (units = 1) with a `sigmoid` activation function (activation = "sigmoid") to model the binary classification problem. The sigmoid activation function maps the output to a range between `0` and `1`, representing the probability of the positive class.
        
        <img src="images/first_model_result.PNG" alt="Alternative text" />

        * The second neural network model named *`second_model`*, is a three-layer architecture with a specific choice for the number of neurons, layers, and activation functions. By selecting 50 neurons in the first hidden layer (units_1 = 50), 100 neurons in the second hidden layer (units_2 = 100), 200 neurons in the second hidden layer (units_2 = 200), and using the `ReLU` activation function (activation = "relu") for all the hidden layers. The number of epoch for the *`second_model`* were set 75. The choice of ReLU activation helps introduce non-linearity and allows the model to learn complex relationships between the input features and the target variable.

        <img src="images/second_model.PNG" alt="Alternative text" />
        
        I used a single neuron in the output layer (units = 1) with a `sigmoid` activation function (activation = "sigmoid") to model the binary classification problem. The sigmoid activation function maps the output to a range between `0` and `1`, representing the probability of the positive class.
        
        <img src="images/second_model_result.PNG" alt="Alternative text" />
    
  * Were you able to achieve the target model performance?
    
     * As you can see in the third I was only able to achieve 73%, which was not the target model performance which was 75%.

  * What steps did you take in your attempts to increase model performance?
    1.  **Increasing the number of neurons and epochs:**
      * By increasing the number of neurons in a layer, the model becomes more expressive and can capture complex patterns in the data. This allows for better representation of the underlying relationships between the features and the target variable, potentially leading to higher accuracy.
      
      * Increasing the number of epochs gives the model more opportunities to learn from the data and adjust the weights. It allows the model to refine its predictions and find better parameter values, which can lead to improved accuracy. However, it's important to find a balance as increasing epochs excessively can lead to overfitting.
    
    2. Removing only `EIN` and not `NAME` column:
      * In the first neural network i.e. *`simple_model`*, I removed both the `EIN` and `NAME` columns as instructed, which resulted in 73% accuracy, but in the optimization notebook, I only removed the `EIN` column, which helped in improving the accuracy from `73%` to `76%`.
      
     <img src='images/dropping_EIN.PNG' alt="Alternative text" />
     
     <img src='images/NAME_value_counts.PNG' alt="Alternative text" />


## 3. Summary:

The model built at the start, without the `EIN` and `NAME` columns, did not perform well and only gave an accuracy of `73%`. In an attempt to optimize the model, or increase the accuracy of the model, when I kept the `NAME` column and also added some extra hidden layers along with increased the number of neurons, I was finally able to acheive an accuracy greater than `75%`.

---